name: publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write   # 关键：允许获取 OIDC token

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - name: Update npm
        run: npm install -g npm@latest

      - name: Publish
        run: npm stage publish --access public
        # 注意：不再需要 env: NODE_AUTH_TOKEN
